version: 2

# 指定构建过程中使用的 Python 版本
# python:
#   version: 3.10

# 指定构建命令
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# # 指定构建成功后的通知方式
# notifications:
#   email:
#     recipients:
#       - your-email@example.com