theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
    include_homepage_in_sidebar: True  # 在侧边栏菜单中列出主页。
    prev_next_buttons_location: bottom # 设置 “Next” 和 “Previous” 按钮的位置：bottom, top, both , or none
    navigation_depth: 4 # 侧边栏导航标题最大层级，默认4
    collapse_navigation: True # 只在当前页面的侧边栏中包含页面标题。
    titles_only: False # 只在侧边栏中包括文章标题，不包括所有子标题。默认值:False。
    sticky_navigation: True #侧边栏在滚动页面时随主页内容滚动

nav:
    - 主页: index.md
    - 系统简介: 1_系统说明/system.md
    - 使用流程: 2_使用流程/flow.md
    - Matrix: 3_接口说明/Matrix/matrix.md
    - Generator: 3_接口说明/策略/generator.md
    - Strategy: 3_接口说明/策略/strategy.md
    - Evaluator: 3_接口说明/评价/evaluator.md
    - DataApi: 3_接口说明/数据模型/set_model_view.md
    - 订单与撮合: 4_其他组件/market_components.md
    - 定制化模块-因子开发: 5_定制化模块_截面因子开发/signal.md
    # <!-- - 定制化模块: 模型训练: 10_机器学习容器/torch.md -->
    - 配置文件与灵活部署: 6_参数配置/configer.md
    - 批量任务流: 9_workflow/batch.md
    - 参数优化: 9_workflow/optim.md
    - 代码样例: 8_测例代码/index.md
    - 数据库: 3_接口说明/数据库/DatabaseAPI.md
    - 可视化: 7_可视化模块/plot.md
    - 更新日志: 11_更新日志/relaerse_note.md
    
site_name: TransMatrix说明文档
repo_url: https://github.com/shichunl/TransMatrixAPI.github.io.git  # 仓库地址
repo_name: TransMatrixAPI.github.io # 仓库名称
edit_uri: docs/ # 编辑路径
site_author: Transwarp # 作者
# copyright: # 版权声明
